In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data/sleep.csv")
df.head()

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia

In [3]:
df.dtypes

person_id                    int64
gender                         str
age                          int64
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [4]:
df['age']=df['age'].astype('int16')
df.dtypes

person_id                    int64
gender                         str
age                          int16
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [5]:
df['gender']=df['gender'].astype('category')
df.dtypes

person_id                     int64
gender                     category
age                           int16
occupation                      str
sleep_duration              float64
sleep_quality               float64
physical_activity_level       int64
stress_level                  int64
bmi_category                    str
blood_pressure                  str
heart_rate                    int64
daily_steps                   int64
sleep_disorder                  str
dtype: object

In [6]:
import numpy as np

In [7]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
person_id,1,2,3,4,5,6,7,8,9,10,...,391,392,393,394,395,396,397,398,399,400
gender,Male,Female,Male,Male,Male,Female,Male,Male,Male,Female,...,Male,Male,Female,Female,Male,Female,Female,Female,Female,Male
age,29,43,44,29,67,47,22,49,25,51,...,47,61,18,28,48,36,45,30,41,37
occupation,Manual Labor,Retired,Retired,Office Worker,Retired,Student,Office Worker,Office Worker,Manual Labor,Retired,...,Retired,Office Worker,Manual Labor,Manual Labor,Retired,Student,Manual Labor,Student,Retired,Retired
sleep_duration,7.4,4.2,6.1,8.3,9.1,6.1,5.1,10.7,11.9,8.2,...,7.6,9.1,8.2,9.9,4.7,4.5,6.0,5.3,11.0,5.8
sleep_quality,7.0,4.9,6.0,10.0,9.5,6.9,6.1,6.2,7.2,4.0,...,8.7,7.1,6.9,10.0,4.7,7.9,6.1,6.5,9.1,7.0
physical_activity_level,41,41,107,20,19,24,26,49,27,64,...,47,69,68,19,108,73,72,58,73,41
stress_level,7,5,4,10,4,4,6,8,8,5,...,10,2,3,3,9,7,8,10,9,6
bmi_category,Obese,Obese,Underweight,Obese,Overweight,Normal,Obese,Obese,Underweight,Overweight,...,Normal,Normal,Normal,Obese,Obese,Normal,Obese,Obese,Obese,Normal
blood_pressure,124/70,131/86,122/70,124/72,133/78,123/60,121/70,134/87,112/63,125/84,...,123/68,130/75,109/61,124/75,134/92,118/66,132/80,125/76,130/75,118/70
heart_rate,91,81,81,55,97,87,66,59,99,76,...,79,61,59,93,60,64,65,66,75,51
daily_steps,8539,18754,2857,6886,14945,9485,15680,18767,16397,12744,...,8226,16330,6891,6992,3961,14497,12848,15255,6567,18079
sleep_disorder,NaN,NaN,NaN,NaN,Insomnia,NaN,NaN,NaN,Sleep Apnea,NaN,...,NaN,Insomnia,Insomnia,NaN,Insomnia,Sleep Apnea,Insomnia,Insomnia,Sleep Apnea,NaN

In [8]:
df.head()

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia

In [9]:
df=pd.read_csv("data/sleep.csv")
df.head()

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia

In [11]:
df=df[['person_id','blood_pressure']]
df.head()

   person_id blood_pressure
0          1         124/70
1          2         131/86
2          3         122/70
3          4         124/72
4          5         133/78

In [14]:
type(['blood_pressure'])

list

In [18]:
df['blood_pressure'].str.split('/',expand=True)

       0   1
0    124  70
1    131  86
2    122  70
3    124  72
4    133  78
..   ...  ..
395  118  66
396  132  80
397  125  76
398  130  75
399  118  70

[400 rows x 2 columns]

In [21]:
df[['high','low']]=df['blood_pressure'].str.split('/',expand=True)
df

     person_id blood_pressure high low
0            1         124/70  124  70
1            2         131/86  131  86
2            3         122/70  122  70
3            4         124/72  124  72
4            5         133/78  133  78
..         ...            ...  ...  ..
395        396         118/66  118  66
396        397         132/80  132  80
397        398         125/76  125  76
398        399         130/75  130  75
399        400         118/70  118  70

[400 rows x 4 columns]

In [22]:
df.dtypes

person_id         int64
blood_pressure      str
high                str
low                 str
dtype: object

In [24]:
df['high']=df['high'].astype('int64')
df['low']=df['low'].astype('int64')

In [25]:
df.dtypes

person_id         int64
blood_pressure      str
high              int64
low               int64
dtype: object

# 数据分箱

In [26]:
import  pandas as pd

In [27]:
df=pd.read_csv("data/employees.csv")

In [38]:
df1=df.head(10)[['employee_id','salary']]
print(df1['salary'].min())
print(df1['salary'].max())

4200.0
24000.0

In [33]:
pd.cut(df1['salary'],bins=2)

0    (14100.0, 24000.0]
1    (14100.0, 24000.0]
2    (14100.0, 24000.0]
3     (4180.2, 14100.0]
4     (4180.2, 14100.0]
5     (4180.2, 14100.0]
6     (4180.2, 14100.0]
7     (4180.2, 14100.0]
8     (4180.2, 14100.0]
9     (4180.2, 14100.0]
Name: salary, dtype: category
Categories (2, interval[float64, right]): [(4180.2, 14100.0] < (14100.0, 24000.0]]

In [41]:
pd.qcut(df1['salary'],3).value_counts()

salary
(4199.999, 6000.0]    4
(6000.0, 12000.0]     3
(12000.0, 24000.0]    3
Name: count, dtype: int64