In [2]:
import pandas as pd

In [5]:
d=pd.Timestamp('2015-05-6 10:22')
d

Timestamp('2015-05-06 10:22:00')

In [7]:
print(type(d))

<class 'pandas.Timestamp'>

In [8]:
d.year

2015

In [9]:
d.month

5

In [10]:
d.minute

22

In [11]:
d.second

0

In [12]:
d.quarter

2

In [13]:
d.is_leap_year

False

In [14]:
d.is_month_start

False

In [15]:
d.day_name()

'Wednesday'

In [19]:
print(d.to_period('M'))

2015-05

In [21]:
print(d.to_period('Y'))

2015

In [23]:
a=pd.to_datetime('2015-05-6 10:22')
print(a)
type(a)

2015-05-06 10:22:00

pandas.Timestamp

In [55]:
df=pd.read_csv("data/weather.csv")
df

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [56]:
df['datetime']=pd.to_datetime(df['date'])

In [57]:
df

            date  precipitation  temp_max  temp_min  wind  weather   datetime
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle 2012-01-01
1     2012-01-02           10.9      10.6       2.8   4.5     rain 2012-01-02
2     2012-01-03            0.8      11.7       7.2   2.3     rain 2012-01-03
3     2012-01-04           20.3      12.2       5.6   4.7     rain 2012-01-04
4     2012-01-05            1.3       8.9       2.8   6.1     rain 2012-01-05
...          ...            ...       ...       ...   ...      ...        ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain 2015-12-27
1457  2015-12-28            1.5       5.0       1.7   1.3     rain 2015-12-28
1458  2015-12-29            0.0       7.2       0.6   2.6      fog 2015-12-29
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun 2015-12-30
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun 2015-12-31

[1461 rows x 7 columns]

In [58]:
df['datetime'].dt.day_name()
df

            date  precipitation  temp_max  temp_min  wind  weather   datetime
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle 2012-01-01
1     2012-01-02           10.9      10.6       2.8   4.5     rain 2012-01-02
2     2012-01-03            0.8      11.7       7.2   2.3     rain 2012-01-03
3     2012-01-04           20.3      12.2       5.6   4.7     rain 2012-01-04
4     2012-01-05            1.3       8.9       2.8   6.1     rain 2012-01-05
...          ...            ...       ...       ...   ...      ...        ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain 2015-12-27
1457  2015-12-28            1.5       5.0       1.7   1.3     rain 2015-12-28
1458  2015-12-29            0.0       7.2       0.6   2.6      fog 2015-12-29
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun 2015-12-30
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun 2015-12-31

[1461 rows x 7 columns]

In [59]:
# df['date'].dt.day_name()

In [60]:
df.set_index('datetime',inplace=True)

In [61]:
df

                  date  precipitation  temp_max  temp_min  wind  weather
datetime
2012-01-01  2012-01-01            0.0      12.8       5.0   4.7  drizzle
2012-01-02  2012-01-02           10.9      10.6       2.8   4.5     rain
2012-01-03  2012-01-03            0.8      11.7       7.2   2.3     rain
2012-01-04  2012-01-04           20.3      12.2       5.6   4.7     rain
2012-01-05  2012-01-05            1.3       8.9       2.8   6.1     rain
...                ...            ...       ...       ...   ...      ...
2015-12-27  2015-12-27            8.6       4.4       1.7   2.9     rain
2015-12-28  2015-12-28            1.5       5.0       1.7   1.3     rain
2015-12-29  2015-12-29            0.0       7.2       0.6   2.6      fog
2015-12-30  2015-12-30            0.0       5.6      -1.0   3.4      sun
2015-12-31  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

# 时间间隔

In [62]:
df

                  date  precipitation  temp_max  temp_min  wind  weather
datetime
2012-01-01  2012-01-01            0.0      12.8       5.0   4.7  drizzle
2012-01-02  2012-01-02           10.9      10.6       2.8   4.5     rain
2012-01-03  2012-01-03            0.8      11.7       7.2   2.3     rain
2012-01-04  2012-01-04           20.3      12.2       5.6   4.7     rain
2012-01-05  2012-01-05            1.3       8.9       2.8   6.1     rain
...                ...            ...       ...       ...   ...      ...
2015-12-27  2015-12-27            8.6       4.4       1.7   2.9     rain
2015-12-28  2015-12-28            1.5       5.0       1.7   1.3     rain
2015-12-29  2015-12-29            0.0       7.2       0.6   2.6      fog
2015-12-30  2015-12-30            0.0       5.6      -1.0   3.4      sun
2015-12-31  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [67]:
days=pd.date_range('2025-7-3','2025-7-5')
print(days)

DatetimeIndex(['2025-07-03', '2025-07-04', '2025-07-05'], dtype='datetime64[us]', freq='D')

In [69]:
df=pd.read_csv("data/employees.csv")
df

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110.0

In [72]:
df['employee_id']=df['employee_id'].astype('int64')
df.dtypes

employee_id         int64
first_name            str
last_name             str
email                 str
phone_number          str
job_id                str
salary            float64
commission_pct    float64
manager_id        float64
department_id     float64
dtype: object

In [74]:
print(df.groupby('department_id').groups)

{10.0: [100], 20.0: [101, 102], 30.0: [14, 15, 16, 17, 18, 19], 40.0: [103], 50.0: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 60.0: [3, 4, 5, 6, 7], 70.0: [104], 80.0: [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79], 90.0: [0, 1, 2], 100.0: [8, 9, 10, 11, 12, 13], 110.0: [105, 106]}

In [84]:
df.groupby('department_id').get_group(10)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
100,200,Jennifer,Whalen,JWHALEN,515.123.4444,AD_ASST,4400.0,NaN,101.0,10.0

In [89]:
df2=df.groupby('department_id')[['salary']].mean()
df2

                     salary
department_id
10.0            4400.000000
20.0            9500.000000
30.0            4150.000000
40.0            6500.000000
50.0            3475.555556
60.0            5760.000000
70.0           10000.000000
80.0            8955.882353
90.0           19333.333333
100.0           8600.000000
110.0          10150.000000

In [98]:
df2['salary']=df2['salary'].round(2)
df2=df2.reset_index()

ValueError: cannot insert level_0, already exists

In [99]:
df2.sort_values('salary')

    level_0  index  department_id    salary
4         4      4           50.0   3475.56
2         2      2           30.0   4150.00
0         0      0           10.0   4400.00
5         5      5           60.0   5760.00
3         3      3           40.0   6500.00
9         9      9          100.0   8600.00
7         7      7           80.0   8955.88
1         1      1           20.0   9500.00
6         6      6           70.0  10000.00
10       10     10          110.0  10150.00
8         8      8           90.0  19333.33

In [108]:
df2=df.groupby(['department_id','job_id'])[['salary']].mean()
df2.reset_index()

    department_id      job_id        salary
0            10.0     AD_ASST   4400.000000
1            20.0      MK_MAN  13000.000000
2            20.0      MK_REP   6000.000000
3            30.0    PU_CLERK   2780.000000
4            30.0      PU_MAN  11000.000000
5            40.0      HR_REP   6500.000000
6            50.0    SH_CLERK   3215.000000
7            50.0    ST_CLERK   2785.000000
8            50.0      ST_MAN   7280.000000
9            60.0     IT_PROG   5760.000000
10           70.0      PR_REP  10000.000000
11           80.0      SA_MAN  12200.000000
12           80.0      SA_REP   8396.551724
13           90.0     AD_PRES  24000.000000
14           90.0       AD_VP  17000.000000
15          100.0  FI_ACCOUNT   7920.000000
16          100.0      FI_MGR  12000.000000
17          110.0  AC_ACCOUNT   8300.000000
18          110.0      AC_MGR  12000.000000