In [3]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv('data/penguins.csv')
df.head()
df.describe()
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [8]:
print(df.isna().sum())

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [9]:
df.dropna(inplace=True)

In [10]:
print(df.isna().sum())

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [11]:
len(df)

333

In [12]:
df.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    str
 1   island             333 non-null    str
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 26.7 KB

In [15]:
df['sex']=df['sex'].astype('category')

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    str
 1   island             333 non-null    str
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    category
dtypes: category(1), float64(4), str(2)
memory usage: 22.8 KB

In [17]:
df['bill_ratio']=df['bill_length_mm']/df['bill_depth_mm']
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767
...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,3.445255
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,3.272727
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,3.210191
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,3.054054
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,3.099379

In [27]:
# 分箱 把体重分成三个等级
labels =['低','中','高']
df['mass_level']=pd.cut(df['body_mass_g'],bins=3,labels=labels)

In [28]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio,mass_level
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909,低
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115,低
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889,低
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554,低
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767,低
...,...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,3.445255,中
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,3.272727,中
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,3.210191,高
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,3.054054,高
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,3.099379,高

In [29]:
df['mass_level'].value_counts()

mass_level
低    150
中    128
高     55
Name: count, dtype: int64

In [30]:
# 按岛屿，性别分组
df.groupby(['sex']).agg({
    'body_mass_g':['mean','count']
})

        body_mass_g
               mean count
sex
Female  3862.272727   165
Male    4545.684524   168

In [32]:
# 按岛屿，性别分组
df.groupby(['island','sex']).agg({
    'body_mass_g':['mean','count']
})

                  body_mass_g
                         mean count
island    sex
Biscoe    Female  4319.375000    80
          Male    5104.518072    83
Dream     Female  3446.311475    61
          Male    3987.096774    62
Torgersen Female  3395.833333    24
          Male    4034.782609    23