In [1]:
import pandas as pd

In [6]:
df1=pd.DataFrame(data={'a':[1,2],'b':[4,5]},
                 index=[1,2])
df2=pd.Series(data=[7,10],index=[1,2],name='a')

In [7]:
df1

   a  b
1  1  4
2  2  5

In [8]:
df2

1     7
2    10
Name: a, dtype: int64

In [10]:
pd.concat([df1,df2])

    a    b
1   1  4.0
2   2  5.0
1   7  NaN
2  10  NaN

In [11]:
pd.concat([df1,df2],axis=1)

   a  b   a
1  1  4   7
2  2  5  10

# dataframe+dataframe

In [13]:
df1=pd.DataFrame(data={'a':[1,2],'b':[4,5]},index=[1,2])
df2=pd.DataFrame(data={'a':[7,8],'b':[10,11]},index=[1,2])

In [14]:
df1

   a  b
1  1  4
2  2  5

In [15]:
df2

   a   b
1  7  10
2  8  11

In [16]:
pd.concat([df1,df2])

   a   b
1  1   4
2  2   5
1  7  10
2  8  11

In [17]:
pd.concat([df1,df2],axis=1)

   a  b  a   b
1  1  4  7  10
2  2  5  8  11

# 重置索引

In [22]:
df1=pd.DataFrame(data={'a':[1,2],'b':[4,5]},index=[1,2])
df2=pd.DataFrame(data={'a':[7,8],'b':[10,11]},index=[1,2])

In [23]:
pd.concat([df1,df2])

   a   b
1  1   4
2  2   5
1  7  10
2  8  11

In [24]:
pd.concat([df1,df2],ignore_index=True)

   a   b
0  1   4
1  2   5
2  7  10
3  8  11

In [25]:
df1=pd.DataFrame(data={'a':[1,2],'b':[4,5]},index=[1,2])
df2=pd.DataFrame(data={'b':[7,8],'c':[10,11]},index=[2,3])

In [26]:
df1

   a  b
1  1  4
2  2  5

In [27]:
df2

   b   c
2  7  10
3  8  11

In [28]:
pd.concat([df1,df2])

     a  b     c
1  1.0  4   NaN
2  2.0  5   NaN
2  NaN  7  10.0
3  NaN  8  11.0

In [31]:
pd.concat([df1,df2],join='inner').loc[2]

   b
2  5
2  7